1 stdcall iopen(str)
@ stdcall iclose(long)
@ stub iprintf
@ stub ivprintf
@ stub isprintf
@ stub isvprintf
@ stub iscanf
@ stub ivscanf
@ stub isscanf
@ stub isvscanf
@ stub ipromptf
@ stub ivpromptf
@ stub ifwrite
@ stub ifread
@ stub iflush
@ stub isetbuf
@ stdcall iwrite(long ptr long long ptr)
@ stdcall iread(long ptr long long ptr)
@ stdcall itermchr(long long)
@ stub igettermchr
@ stdcall ionsrq(long ptr)
@ stub igetonsrq
@ stub ionintr
@ stub igetonintr
@ stub isetintr
@ stub iintron
@ stub iintroff
@ stub iwaithdlr
@ stub ilock
@ stub iunlock
@ stub isetlockwait
@ stub igetlockwait
@ stdcall itimeout(long long)
@ stub igettimeout
@ stub iabort
@ stdcall iclear(long)
@ stdcall ihint(long long)
@ stub ilocal
@ stdcall ireadstb(long ptr)
@ stub iremote
@ stub isetstb
@ stub itrigger
@ stub ixtrig
@ stub igetaddr
@ stub igetdevaddr
@ stub igetintftype
@ stub igetsesstype
@ stdcall igetintfsess(long)
@ stub igetlu
@ stub igetlulist
@ stub igetluinfo
@ stub ibeswap
@ stub ileswap
@ stub iswap
@ stub isetdata
@ stub igetdata
@ stub iversion
@ stub igpibatnctl
@ stub igpibbusaddr
@ stdcall igpibbusstatus(long long ptr)
@ stub igpibllo
@ stub igpibpassctl
@ stdcall igpibppoll(long ptr)
@ stub igpibppollconfig
@ stub igpibppollresp
@ stub igpibrenctl
@ stdcall igpibsendcmd(long ptr long)
@ stub iserialbreak
@ stub iserialctrl
@ stub iserialmclctrl
@ stub iserialmclstat
@ stub iserialstat
@ stub ivxibusstatus
@ stub ivxitrigon
@ stub ivxitrigoff
@ stub ivxitrigroute
@ stub ivxigettrigroute
@ stub ivxirminfo
@ stub ivxiservants
@ stub ivxiwaitnormop
@ stub ivxiws
@ stub imap
@ stub iunmap
@ stub imapinfo
@ stub ibblockcopy
@ stub iwblockcopy
@ stub ilblockcopy
@ stub ibpushfifo
@ stub iwpushfifo
@ stub ilpushfifo
@ stub ibpopfifo
@ stub iwpopfifo
@ stub ilpopfifo
@ stdcall ionerror(ptr)
@ stub igetonerror
@ stdcall I_ERROR_EXIT(long long)
@ stdcall I_ERROR_NO_EXIT(long long)
@ stdcall igeterrno()
@ stub igeterrstr
@ stub icauseerr
@ stub igpiostat
@ stub igpioctrl
@ stub igpiosetwidth
@ stub igpiogetwidth
@ stub icmd
@ stub itrace
@ stub isetcscpidata
@ stub igetcscpidata
@ stub isetubuf
@ stub igetgatewaytype
@ stdcall _siclcleanup()
@ stub imsibeventmask
@ stub imsibcmd
@ stub imsibseterror
@ stub imsibclearerror
@ stub imsibinfo
@ stub imsibmodule
@ stub imsibsetstb
@ stub igpibgett1delay
@ stub igpibsett1delay
@ stub idrvrversion
@ stub ilantimeout
@ stub ilangettimeout
@ stub sicl_put_log
@ stub igpibpulseifc
@ stub igetvberrbase
@ stub isetvberrbase
@ stub ibpoke
@ stub iwpoke
@ stub ilpoke
@ stub ibpeek
@ stub iwpeek
@ stub ilpeek
@ stub igetblockmode
@ stub callback_log
@ stub imapx
@ stub iunmapx
@ stub iderefptr
@ stub ipeekx8
@ stub ipeekx16
@ stub ipeekx32
@ stub ipokex8
@ stub ipokex16
@ stub ipokex32
@ stub iblockmovex
@ stub ipeekx64
@ stub ipokex64
@ stub ivximacro
@ stub sicl_read_hw_info
@ stub sicl_open_hwconfig
@ stub sicl_getnext_hwconfig
@ stub sicl_close_hwconfig
@ stub hwconfig_init
@ stub hwconfig_deinit
@ stub iusbcontrolin
@ stub iusbcontrolout
@ stub iusbgetcapabilities
@ stub iusbgetinfo
@ stub iusbintrgetsize
@ stub iusbintrgetdata
@ stub iusbintrclose
@ stub iusbctrl
@ stub iusbstat
@ stub pil_user_unload_all
201 stub setAttributeBoolean

